### ISSUE TITLE
Request to IdentityServer3 OWIN middleware never completes

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [SuaveIO/suave#435]
I am trying to embed the IdentityServer3 owin middleware into my suave.io application. When I make a request to any of IdentityServer3's endpoints, I get data, but the request never completes. The browser's loading icon continues to spin.

I have an IdentityServerIntegration project in my fork which demonstrates this problem [https://github.com/JohnDoeKyrgyz/suave/tree/master/examples/IdentityServerIntegration](https://github.com/JohnDoeKyrgyz/suave/tree/master/examples/IdentityServerIntegration). One of the endpoints I use in testing is [http://localhost:8083/identity/.well-known/openid-configuration](http://localhost:8083/identity/.well-known/openid-configuration)

Here are Suave's log messages when this happens. NOTE: The entry "Socket error while processing request, exiting: SocketError Shutdown" occurs when I stop the request from the browser.

> [V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:03.3055473Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 96.002 ms with binding 169.254.80.80:8083 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3605506Z: listener started in 96.002 ms with binding ::1:8083 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 96.002 ms with binding 169.254.179.231:8443 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 101.002 ms with binding 169.254.179.231:8083 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 107.002 ms with binding 192.168.1.10:8443 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 122.004 ms with binding 127.0.0.1:8083 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 113.003 ms with binding 192.168.1.10:8083 [Suave.Tcp.tcpIpServer]
[I] 2016-05-07T01:34:03.3595505Z: listener started in 119.003 ms with binding 169.254.80.80:8443 [Suave.Tcp.tcpIpServer]
[V] 2016-05-07T01:34:03.3735522Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2016-05-07T01:34:03.3745515Z: listener started in 142.004 ms with binding ::1:8443 [Suave.Tcp.tcpIpServer]
[V] 2016-05-07T01:34:08.6265799Z: ::1 connected, total: 1 clients [Suave.Tcp.job]
[V] 2016-05-07T01:34:08.6585904Z: reserving buffer: 0, free count: 99 [Suave.Tcp.job] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:08.7046125Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2016-05-07T01:34:08.7105823Z: reading first line of request [Suave.Web.processRequest]
[V] 2016-05-07T01:34:08.7646047Z: reserving buffer: 8192, free count: 98 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:08.8146059Z: reading headers [Suave.Web.processRequest]
[V] 2016-05-07T01:34:08.8216061Z: freeing buffer: 8192, free count: 99 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:08.8386082Z: parsing post data [Suave.Web.processRequest]
[V] 2016-05-07T01:34:08.8526001Z: <- processor [Suave.Web.httpLoop.loop]
[D] 2016-05-07T01:34:08.9366057Z: [GET] http://[::1]:8083/identity/.well-known/openid-configuration []
[V] 2016-05-07T01:34:09.0196064Z: yielding to OWIN middleware [Suave.Owin]
[V] 2016-05-07T01:34:09.4996403Z: suave back in control [Suave.Owin]
[V] 2016-05-07T01:34:09.5046384Z: 'Connection: keep-alive' recurse [Suave.Web.httpLoop.loop]
[V] 2016-05-07T01:34:09.5046384Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2016-05-07T01:34:09.5046384Z: reading first line of request [Suave.Web.processRequest]
[V] 2016-05-07T01:34:09.5046384Z: reserving buffer: 16384, free count: 98 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:14.1882388Z: freeing buffer: 16384, free count: 99 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:14.1892114Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2016-05-07T01:34:14.2282422Z: Socket error while processing request, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2016-05-07T01:34:14.2322410Z: freeing buffer: 0, free count: 100 [Suave.Tcp.job] [Suave.Socket.BufferManager]
[V] 2016-05-07T01:34:14.2322410Z: Shutting down transport. [Suave.Tcp.job]
[V] 2016-05-07T01:34:14.2372099Z: ::1 disconnected, total: 0 clients [Suave.Tcp.job]

**Comment by endeavour** [comment]
I'm having a similar issue with Websharper.Suave, I fixed it by doing something like this:

    let after = Suave.Owin.OwinAppFunc(fun e -> System.Threading.Tasks.Task.FromResult 0 :> _)
    let sitelets = Suave.Owin.OwinApp.ofMidFuncWithNext pathBase
    (SiteletMiddleware<_>.AsMidFunc(Options.Create(rootDirectory, binDirectory), app)) after

I think if you don't explictly close the task the response stream is never closed so the browser just keeps the connection open waiting for more data.

Perhaps the semantics around the Owin integration still aren't quite right?

**Comment by haf** [comment]
@JohnDoeKyrgyz Could you please test this with master?

**Comment by JohnDoeKyrgyz** [comment]
@endeavour, Thanks for the hint. @haf I tried to do what @endeavour is doing, but it did not really work. In my example I am using the AppBuilder class which ends up producing an OwinApp. I have to translate it to an OwinMidFunc to do what @endeavour is doing.

```
let builder = builder.UseIdentityServer(options)
let owinAppMiddleware =
    let middleware = builder.Build()
    let middlewareFunc = new Func<OwinEnvironment, Task>(fun (env : OwinEnvironment) -> (middleware.Invoke env))
    new Func<Func<OwinEnvironment, Task>, Func<OwinEnvironment, Task>>( fun _ -> middlewareFunc )

let pathBase = "/identity"`

let after = Owin.OwinAppFunc(fun e -> Task.FromResult 0 :> _)
Owin.OwinApp.ofMidFuncWithNext pathBase owinAppMiddleware after
```

After some more digging, I think the actual solution is to fix a bug in Owin.fs. The sendHeaders method of the OwinContext is not setting closeConnection to true if the middleware has set the content-length header. This seems incorrect. If the middleware has set the content-length header then Suave should close the connection. The sendHeaders method should be changed from.

```
member x.sendHeaders() = socket{
      headersSent <- true
      // collect headers
      let ctx = x.finalise()
      // NOTE: if there is no content-lenght header we should buffer
      closeConnection <- not (List.exists (fun (p,q) -> String.equalsOrdinalCI p "content-length") ctx.response.headers)
      let! (_, connection) = HttpOutput.writePreamble ctx ctx.connection
      let! (_, connection) = AsyncSocket.asyncWriteLn "" connection
      let! connection = AsyncSocket.flush connection
      return connection
      }
```

to

```
member x.sendHeaders() = socket{
      headersSent <- true
      // collect headers
      let ctx = x.finalise()
      // NOTE: if there is no content-lenght header we should buffer
      closeConnection <- (List.exists (fun (header,_) -> String.equalsOrdinalCI header "content-length") ctx.response.headers)
      let! (_, connection) = HttpOutput.writePreamble ctx ctx.connection
      let! (_, connection) = AsyncSocket.asyncWriteLn "" connection
      let! connection = AsyncSocket.flush connection
      return connection
      }
```

@haf Does this make sense?

**Comment by ademar** [comment]
I am running your branch and do not see this behaviour ?!

```text
[D] 2016-05-09T15:07:00.3933450Z: [GET] http://127.0.0.1:8083/identity/.well-known/openid-configuration []
[V] 2016-05-09T15:07:00.5074120Z: yielding to OWIN middleware [Suave.Owin]
[V] 2016-05-09T15:07:01.0169500Z: suave back in control [Suave.Owin]
[V] 2016-05-09T15:07:01.0195980Z: Connection: close [Suave.Web.httpLoop.loop]
```

**Comment by JohnDoeKyrgyz** [comment]
@ademar Strange. I got a fresh clone of my repo and am still seeing the buggy behavior.

**Comment by ademar** [comment]
There is another difference between your log and mine; the binding `http://[::1]:8083` vs `http://127.0.0.1:8083`.

I am running on OSX and so I wonder if there is something going on with the way the bindings are calculated here https://github.com/JohnDoeKyrgyz/suave/blob/master/examples/IdentityServerIntegration/IdentityServer.fs#L83

**Comment by JohnDoeKyrgyz** [comment]
Spent some more time on this. I think I understand what is going on.

In HttpOutput.fs the writeHeaders function explicitly filters out _server, date_ and _content-length_ from the list of headers being written. For standard Suave requests, the _content-length_ header is written in the writeContent function. Unfortunately, this function is not used when processing owin requests. It appears as if the owin application itself is allowed to send it's body, but the headers are captured, and handled by Suave.

If I comment out part of the HttpOutput.writeHeaders function it works:

```
let inline writeHeaders (headers : (string*string) seq) = withConnection {
  for x,y in headers do
    //if not (List.exists (fun y -> x.ToLower().Equals(y)) ["server";"date";"content-length"]) then
    do! asyncWriteLn (String.Concat [| x; ": "; y |])
  }
```

@haf, @ademar Do you think I am on the right track with this? If so, I will write some unit tests, and take a look at what can be done to make sure that the content-length is sent correctly for Owin requests.
