### ISSUE TITLE
Chinese become garbled when posting data in multipart/form-data

### ISSUE THREAD

**Issue by sun2014cn** [SuaveIO/suave#549]
I want to upload files,
```
<form action="/file" method="post" enctype="multipart/form-data" accept-charset="utf-8">
           <input name="hello" value="文档内容" />
          <input type="file" name="world"/>
         <input type="submit" value="go" />
</form>
```

```
let hello = ctx.request.fieldData "hello"
let upfile = ctx.request.files.[0]
```
**hello** and **upfile.fileName**  become garbled. And I have add   `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`  in `<head>` , it does not work. What I should do?

Thanks

**Comment by haf** [comment]
@sun2014cn You have to send the HTML page as `text/html; charset=utf-8` from the server.

Could you code a failing unit test, you think? It would help in debugging this.

**Comment by sun2014cn** [comment]
@haf My index.html is
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>文档标题</title>
</head>
<body>
    <h1>嗨</h1>
    <form action="/file" method="post" enctype="multipart/form-data" accept-charset="utf-8">
        <input name="hello" value="文档内容" />
        <input type="file" name="world" />
        <input type="submit" value="go" />
    </form>
</body>
</html>
```

And the app.fsx is:
```
open System
open System.IO
open Suave                 // always open suave
open Suave.Successful      // for OK-result
open Suave.Web             // for config
open Suave.Filters
open Suave.Operators
open Suave.Writers

let webRoot = Path.Combine(__SOURCE_DIRECTORY__, "web")

let postFile ctx = async {

  let hello = ctx.request.fieldData "hello"
  let upfile = ctx.request.files.[0]
  let path= webRoot+"\\"+upfile.fileName
  File.Copy(upfile.tempFilePath,path)

  let res =
    match hello with
    |Choice1Of2 suc -> suc
    |Choice2Of2 fail -> fail
  return! ctx |> (Successful.OK res >=> setMimeType "text/html; charset=utf-8")
  }

let app = 
    choose [

        path "/" >=> Files.browseFile webRoot "index.html"
        path "/file" >=> postFile
        Files.browse webRoot
    ]

startWebServer defaultConfig app
```
if I select a file with a Chinese name for the file input, in the  **postFile ctx**  function on server,
**hello** ('文档内容') and **upfile.fileName** become '?????...' in my case and the **File.Copy** failed with the exception : 'Illegal characters in path'

**Comment by ademar** [comment]
@sun2014cn what version of Suave are you running? Have you tried the latest pre-releases of v2.0 ? I think this issue has been fixed on master for a while now.

**Comment by sun2014cn** [comment]
@ademar I run the 1.1.3. But I tried the 2.0.0-rc3 just now, it is still garbled. I will do more try.

**Comment by ademar** [comment]
Managed to reproduce the issue. I am working on the fix.

**Comment by ademar** [comment]
@sun2014cn Can you please try the latest pre-release v2.0.0-rc5. It should be fixed now.

Note that in general there is no reliable way of decoding `filename` and it is not advisable to rely on it (due security reasons among other things).

**Comment by sun2014cn** [comment]
@ademar  I tried the v2.0.0-rc6. It's OK  except the filename Now. 😀.According to your advice,  how to distinguish them if I upload multiple files at the same time . Do you have any idea about it? thanks.

**Comment by ademar** [comment]
> how to distinguish them if I upload multiple files at the same time

There is different ways you could go about it; the simplest you could just count them file1,file2, .. 

> It's OK except the filename

Can you capture an HTTP session so we can look at what the browser is sending ? It would be very easy to do with Wireshark.

**Comment by sun2014cn** [comment]
![Uploading 捕获1.PNG…]()
![Uploading 捕获2.PNG…]()
![Uploading 捕获3.PNG…]()
![Uploading 捕获4.PNG…]()
![Uploading 捕获.PNG…]()
![Uploading 捕获1.PNG…]()
![Uploading 捕获2.PNG…]()
![Uploading 捕获3.PNG…]()
![Uploading 捕获4.PNG…]()

**Comment by sun2014cn** [comment]
This is my wireshark and npcap(running on 127.0.0.1) Test, I'm not familiar with wireshark so I have to capture some screens.
![3](https://cloud.githubusercontent.com/assets/12409401/21488657/780f0498-cc1d-11e6-9733-b27b2a1e82fb.PNG)

![1](https://cloud.githubusercontent.com/assets/12409401/21488666/8556bae2-cc1d-11e6-8ae7-3ed3852c49d3.PNG)

**Comment by ademar** [comment]
Try this, right click on an HTTP entry, select Follow and then Follow HTTP Stream and it will give you the whole HTTP session in text format.

**Comment by sun2014cn** [comment]
@ademar 

```
GET / HTTP/1.1
Host: localhost:8083
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
If-Modified-Since: Fri, 23 Dec 2016 09:48:34 GMT
Cache-Control: max-age=0

HTTP/1.1 304 Not Modified
Server: Suave (https://suave.io)
Date: Tue, 27 Dec 2016 02:40:57 GMT
Content-Type: text/html
Content-Length: 0

POST /file HTTP/1.1
Host: localhost:8083
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:8083/
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Content-Type: multipart/form-data; boundary=---------------------------266292648924049
Content-Length: 13639

-----------------------------266292648924049
Content-Disposition: form-data; name="hello"

............
-----------------------------266292648924049
Content-Disposition: form-data; name="world"; filename="............ - ..........doc"
Content-Type: application/msword

........................>...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
...........
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................R.o.o.t. .E.n.t.r.y............................................................................F............Pc....................S.u.m.m.a.r.y.I.n.f.o.r.m.a.t.i.o.n...........................(.................................................................D.o.c.u.m.e.n.t.S.u.m.m.a.r.y.I.n.f.o.r.m.a.t.i.o.n...........8...............................................................W.o.r.d.D.o.c.u.m.e.n.t.............................................................................................................................................
...........
........................................................................... ...!..."...#...$...%...&...'...(...)...*...+...,...-......./...0...1...2...3...4...5...6...7...8...9...:...;...<...=...>...?...@...A...B...C...D...E...F...G...H...I...J............................................................................................................................................................................................................................................................Oh.....+'..0.......................................................................................8.......H...
...T.......`.......l.......t.......|...................................................wmjm...b........................u.s.e.r.....................................N.o.r.m.a.l...d.o.t.m...........y.u.b.a.o.s.h.i.............6.8.....@.....|..C..@....._.....@......W ...................................M.i.c.r.o.s.o.f.t. .O.f.f.i.c.e. .W.o.r.d...................................................................+,..D...............+,..\...................................................................................................................
...................................................................................................................................................................................(.......\.......d.......l...............K.S.O.P.r.o.d.u.c.t.B.u.i.l.d.V.e.r.............................2.0.5.2.-.1.0...1...0...5.4.5.7.................0.T.a.b.l.e.....................................................................................................................D.a.t.a.........................................................
..........................................................................................................................................................................................................................................................................................................................................P......................KSKS........................................................................................................................2.......2...................................!...............................................2.......N...............w...0...................................................................................................................Y
..$.......h.......J...b.......................................................P...^...........................................................................5.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................}
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................egqwm.m.s.X.vKm.z
.wmjm.mo`
..e.... . . . .t^ . ..g . ..e . ..e . . . . . . . . . . . . . . . . . . .~{.S.. . . . . . . . . .
...
. . . .wmjm.mo` .
.
.
.
.
.
.
.
.
.
.
..S._..
. . . ..egq.^wm.m.N.n.N@\
...
.T..|.N.. . . . . . . . . . . . . . . . . . . . . . .5u..(. O.w)...0.6.3.3.-.3.3.8.2.3.8.3...
...........................................................................................................................................................................................................................................$...,.......0...2...4...6...8...:...>...l...~..............}g[MA3..............CJ..OJ..PJ..QJ..o(.aJ..>*...CJ..OJ..PJ..QJ..o(.aJ...CJ..OJ..PJ..QJ..o(.aJ..>*...CJ..OJ..PJ..QJ..o(.aJ..*CJ..OJ..PJ..QJ..o(.aJ..>*.mH..sH..nH..tH....CJ..OJ..PJ..QJ..o(.aJ..>*...CJ..o(.aJ..\...!CJ..o(.aJ..>*.mH..sH..nH..tH..\...CJ..o(.aJ..>*.\...CJ..o(.aJ..\...!CJ..o(.aJ..>*.mH..sH..nH..tH..\...CJ..o(.aJ..\....CJ4.o(.aJ4.5..\...CJ4.o(.aJ4.5..nH..tH..\...CJ4.o(.aJ4.5..\...CJ$.o(.aJ$.5..\...CJ$.o(.aJ$.5..\....~..........................................................................................................}wqia[U.........................................................CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ..5....CJ..o(.aJ..5....CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ..o(.aJ...CJ .o(.aJ .5....CJ .o(.aJ .5....CJ .OJ..QJ..o(.aJ .5..nH..tH....CJ .o(.aJ .5....CJ .o(.aJ ..CJ .o(.aJ ..CJ..o(.aJ..mH..sH..nH..tH..U....CJ..OJ..PJ..QJ..o(.aJ..>*................*...,............................................................................................................................................................................................................................................................................................................................................................CJ..aJ...6B*.`J..ph....CJ..OJ..PJ..o(.aJ..5..mH..sH..nH..tH..U....CJ..o(.aJ...CJ..o(.aJ..6B*.`J..ph....CJ..OJ..PJ..o(.aJ..5..mH..sH..nH..tH..U.........................................................................................................................................................................................................................................................................WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....WD....X.`.X.....d....a$..$...d.\$......d....a$..$......d....
...........d....a$..$...d.\$.
...........d......d.\$.
....r .....................................................................................................................................................................................................................................................................................................................................................................................................................................................WD....X.`.X.....WD....2.`.2.....WD....X.`.X.....WD....Z.`.Z.....WD....X.`.X...,..... ..A!...#..."...$...%.....S.....2P..1.8...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................&...............................................................6...6...6...6...6...6...6...6...6...v...v...v...v...v...v...v...v...v...6...6...6...........6...>...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6.......6...6.......6...6...6...6...6...6...6...6.......6...6...6...6...6...6...6...6...6...6...6...6...h...H...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...4...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...6...4.......6...6...6........................... ...0...@...P...`...p...................................6...6...6...6... ...0...@...P...`...p................................... ...0...@...P...`...p................................... ...0...@...P...`...p................................... ...0...@...P...`...p................................... ...0...@...P...`...p................................... ...0...@...P...`...p...........F..@....F.............ck.e......a$..$.1$....CJ..KH..mH..sH..nH..tH.._H....................$.A@....$..................k=.W[SO....N.i@....N.........0...nf..h.<h..(.:V..4........4......l.4........4......l.............8..O....8.........0.
.yb.lFh.e,g .C.h.a.r.....CJ..aJ..KH.....@..................u..w..c....d....a$..$.G$.@&.$d....N..........%d....O..........&d....P..........'d....Q..........
....9.r .....CJ..OJ..QJ..8. @....8.............u.........a$..$.G$.
....9.r ....CJ.....@.."...........0...yb.lFh.e,g........CJ..aJ......~....................................................................G................z. ....................T.i.m.e.s. .N.e.w. .R.o.m.a.n...-......................(.................[SO..;.......................................W.i.n.g.d.i.n.g.s...7.......................................NS.e.[SO...[SO..A4...
..................................wiSO_.G.B.2.3.1.2...wiSO..............wmjm...b........u.s.e.r...y.u.b.a.o.s.h.i..................... ............Qh.....^2.gT.E.9.Eg..................................................!.........Z.&.!.).,...:.;.?.].}.......... . . . & 6".0.0.0.0.0.0
0.0.0.0.0..................=.@.\.].^...................................................................................................................(.[.{.... . .0
0.0.0.0.0.0....;.[.........................................................................................................................................................................................................................)......?..................................'*......2.....................I...I...........I.......I.......c........................>...2..y^
......?..>'...O...Z..*r.."
...J......x....0.......i...M...V...~#.%`$..g&.c.*.../.y.0...2.:99..b9.V.?.1^B..eI..sK.aHL.|.M..DY."P[.E/].4e]...a..qb..:g..Hg..Rh..'l.KKl..Jo. 9u.m<v...y.._{..l{...~...~.F...D...O.......NG..[...O/.......o...#.._f.......Q...#.......m...Z..........n1...l..C........K...M...$...o..Kz..@`......./..v....H...e..........73..zN..LJ..1...!...?...."..>W...~..n..2..:A........................(....... ........................................................................(.............................
.................l...B.
..........
......:.................(.)...........................
....v.~ .2....."...........................l...B.
..........
......:.................(.)...........................
....v.~ .4....."...........................l...B.
..........
......:.................(.)...........................
....v.~ .5....."...........................6.....
.............S...............................?.....@...f...................Y...7"......t.........w........#......t.........w........#..=...t......@................................................................................................................................................................................................................................................................................................................................................
-----------------------------266292648924049--
HTTP/1.1 200 OK
Server: Suave (https://suave.io)
Date: Tue, 27 Dec 2016 02:41:09 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 28

???????????? - ?????????.doc
```

**Comment by ademar** [comment]
@sun2014cn I've just pushed v2.0.0-rc7, can you please give it a try ?

**Comment by sun2014cn** [comment]
@ademar  I‘ve tried it, the filename is OK now.
But I ran into another problem. If I post the form(for example  **hello** :文档内容；**world**:海浪消息 - 规范化.doc) then back to the form page and modify the hello input , select another file(for example **hello**:yyyy  ;**file**:yyyy.txt),I still get the last result(文档内容;海浪消息 - 规范化.doc). In  wireshark , it sends right data, but on server it gets the data I send at the first time(the hello and filename doesn't change).
But If I wait for a while for posting, it may change. Is it a bug or I miss something?

**Comment by ademar** [comment]
@sun2014cn Please try the latest rc8. Thanks for standing by.

**Comment by sun2014cn** [comment]
@ademar They work correctly now. We all love suave.

**Comment by haf** [comment]
Nice, well done. Tweeting the release now https://github.com/SuaveIO/suave/releases/tag/v2.0.0-rc8
